import {describe,it,expect,vi,beforeEach} from 'vitest';
import {encodeFunctionData,encodeAbiParameters,encodeEventTopics,getAddress,type Address,type Hex} from 'viem';
const mocks=vi.hoisted(()=>({inspect:vi.fn(),validateNewOwner:vi.fn(),client:vi.fn(),ensCheck:vi.fn()}));
vi.mock('../src/chain',async importOriginal=>({...await importOriginal<typeof import('../src/chain')>(),clientFor:mocks.client}));
vi.mock('../src/wallet',async importOriginal=>({...await importOriginal<typeof import('../src/wallet')>(),inspect:mocks.inspect,validateNewOwner:mocks.validateNewOwner}));
vi.mock('../src/ens',async importOriginal=>({...await importOriginal<typeof import('../src/ens')>(),assertNameUnchanged:mocks.ensCheck}));
import {connect,watchConnection,previewRecovery,submit,assertExecutionReceipt,type Connection,type Preview} from '../src/signing';
import {decodeOwner,type Snapshot} from '../src/wallet';
import {NETWORKS} from '../src/chain';
import {walletAbi} from '../src/abi';
import trusted from '../src/trusted-code.json';
const wallet=getAddress('0xbec9c3d164e2e8c640dc8efc330e92bafa6e7b07'),owner=getAddress('0x1111111111111111111111111111111111111111'),backup=getAddress('0x2222222222222222222222222222222222222222');
const hash=('0x'+'aa'.repeat(32)) as Hex;
const event=[{type:'event',name:'UserOperationEvent',inputs:[{name:'userOpHash',type:'bytes32',indexed:true},{name:'sender',type:'address',indexed:true},{name:'paymaster',type:'address',indexed:true},{name:'nonce',type:'uint256',indexed:false},{name:'success',type:'bool',indexed:false},{name:'actualGasCost',type:'uint256',indexed:false},{name:'actualGasUsed',type:'uint256',indexed:false}]}] as const;
function operation(sender:Address,success:boolean){return {address:trusted.entryPoint,data:encodeAbiParameters([{type:'uint256'},{type:'bool'},{type:'uint256'},{type:'uint256'}],[0n,success,2n,3n]),topics:encodeEventTopics({abi:event,eventName:'UserOperationEvent',args:{userOpHash:hash,sender,paymaster:owner}})}}
function snapshot():Snapshot{return {wallet,chainId:1,block:100n,implementation:trusted.implementation as Address,implementationHash:trusted.implementationHash as Hex,proxyHash:trusted.proxyHash as Hex,verified:true,nextIndex:1n,count:1n,owners:[decodeOwner(0,encodeAbiParameters([{type:'address'}],[owner]))],native:100n,entryPoint:trusted.entryPoint as Address,entryPointHash:trusted.entryPointHash as Hex,deposit:20n,stake:0n,checkedAt:Date.now()}}
function preview():Preview{return {kind:'addition',snapshot:snapshot(),actor:wallet,route:'self',data:encodeFunctionData({abi:walletAbi,functionName:'addOwnerAddress',args:[backup]}),calls:[],newOwner:backup,newOwnerContract:false,notes:[],createdAt:Date.now(),resolvedTargets:[{name:'backup.eth',address:backup}]}}
beforeEach(()=>{vi.clearAllMocks();mocks.inspect.mockResolvedValue(snapshot());mocks.validateNewOwner.mockResolvedValue({isContract:false});mocks.ensCheck.mockResolvedValue(undefined);mocks.client.mockReturnValue({getBalance:vi.fn().mockResolvedValue(100n),getCode:vi.fn().mockResolvedValue('0x'),call:vi.fn().mockResolvedValue({data:'0x'}),waitForTransactionReceipt:vi.fn().mockResolvedValue({status:'success',logs:[operation(wallet,true)]})})});
describe('Connection lifecycle',()=>{
 it('normalizes the connected account and records its chain',async()=>{const request=vi.fn().mockResolvedValueOnce([wallet.toLowerCase()]).mockResolvedValueOnce('0x1');expect(await connect({request},'test')).toMatchObject({address:wallet,chainId:1})});
 it('ignores identical SDK notifications, preserves actual network changes, and cleans up listeners',()=>{const listeners:Record<string,(data:any)=>void>={};const on=vi.fn((event,handler)=>{listeners[event]=handler}),removeListener=vi.fn();const account=vi.fn(),chain=vi.fn(),disconnected=vi.fn();const stop=watchConnection({address:wallet,name:'test',chainId:1,provider:{request:vi.fn(),on,removeListener}},account,chain,disconnected);listeners.chainChanged('0x1');listeners.accountsChanged([wallet.toLowerCase()]);expect(chain).not.toHaveBeenCalled();expect(account).not.toHaveBeenCalled();listeners.chainChanged('0x2105');expect(chain).toHaveBeenCalledWith(8453);listeners.accountsChanged([owner]);expect(account).toHaveBeenCalledWith(owner);listeners.accountsChanged([]);expect(account).toHaveBeenCalledWith(null);listeners.disconnect(null);expect(disconnected).toHaveBeenCalledTimes(1);stop();expect(removeListener).toHaveBeenCalledTimes(3)});
});
describe('Connected smart account transactions',()=>{
 function provider(accounts=wallet){return {request:vi.fn(async({method}:any)=>{if(method==='eth_accounts')return [accounts];if(method==='eth_chainId')return '0x1';if(method==='eth_sendTransaction')return hash;throw Error('Unexpected request: '+method)})}}
 it('sends the exact reviewed self-call using standard transaction transport',async()=>{const p=preview(),pr=provider(),broadcast=vi.fn();const c:Connection={address:wallet,provider:pr,name:'Smart account'};expect(await submit(c,NETWORKS[0],undefined,p,vi.fn(),broadcast)).toBe(hash);expect(pr.request).toHaveBeenCalledWith({method:'eth_sendTransaction',params:[{from:wallet,to:wallet,data:p.data,value:'0x0',chainId:'0x1'}]});expect(broadcast).toHaveBeenCalledWith(hash,'transaction');expect(mocks.ensCheck).toHaveBeenCalledWith(p.resolvedTargets![0]);expect(pr.request.mock.calls.filter(([r])=>r.method==='eth_sendTransaction')).toHaveLength(1)});
 it('previews and submits a native recovery batch through the connected smart account',async()=>{const p=await previewRecovery(NETWORKS[0],undefined,snapshot(),wallet,backup,[{asset:{key:'native',kind:'native',name:'Ether',symbol:'ETH',decimals:18,balance:100n,source:'test'},amount:20n}]);expect(p.route).toBe('self');expect(p.calls).toEqual([{target:backup,value:20n,data:'0x'}]);const pr=provider();await submit({address:wallet,provider:pr,name:'test'},NETWORKS[0],undefined,p,vi.fn(),vi.fn());expect(pr.request).toHaveBeenCalledWith({method:'eth_sendTransaction',params:[{from:wallet,to:wallet,data:p.data,value:'0x0',chainId:'0x1'}]})});
 it('does not send if the name changes before signing',async()=>{mocks.ensCheck.mockRejectedValue(Error('ENS changed'));const pr=provider();await expect(submit({address:wallet,provider:pr,name:'test'},NETWORKS[0],undefined,preview(),vi.fn(),vi.fn())).rejects.toThrow('ENS changed');expect(pr.request.mock.calls.some(([r])=>r.method==='eth_sendTransaction')).toBe(false)});
 it('does not send if the provider account changes during simulation',async()=>{const pr=provider();let count=0;pr.request.mockImplementation(async({method}:any)=>method==='eth_accounts'?[++count===1?wallet:owner]:'0x1');await expect(submit({address:wallet,provider:pr,name:'test'},NETWORKS[0],undefined,preview(),vi.fn(),vi.fn())).rejects.toThrow('changed');expect(pr.request.mock.calls.some(([r])=>r.method==='eth_sendTransaction')).toBe(false)});
 it('never retries a rejected or ambiguous signing request',async()=>{const pr=provider();pr.request.mockImplementation(async({method}:any)=>{if(method==='eth_accounts')return [wallet];if(method==='eth_chainId')return '0x1';throw Error('Request rejected')});await expect(submit({address:wallet,provider:pr,name:'test'},NETWORKS[0],undefined,preview(),vi.fn(),vi.fn())).rejects.toThrow('Request rejected');expect(pr.request.mock.calls.filter(([r])=>r.method==='eth_sendTransaction')).toHaveLength(1)});
 it('does not report a failed user operation as successful merely because its bundle was mined',()=>{expect(()=>assertExecutionReceipt({status:'success',logs:[operation(wallet,false)]},wallet,trusted.entryPoint as Address)).toThrow('operation failed');expect(()=>assertExecutionReceipt({status:'success',logs:[operation(owner,false),operation(wallet,true)]},wallet,trusted.entryPoint as Address)).not.toThrow();expect(()=>assertExecutionReceipt({status:'reverted'},wallet,trusted.entryPoint as Address)).toThrow('reverted')});
});
