import {describe,it,expect,vi} from 'vitest';
import {getAddress,decodeFunctionData,encodeAbiParameters,encodeFunctionData,type Address,type Hex} from 'viem';
import {decodeOwner,assertSameOwners,assertAddition,assertTrusted,type Snapshot} from '../src/wallet';
import {buildRecovery,amountFor,simulateRecovery,type Asset} from '../src/assets';
import {actorRoute,safeExport,recheckPreview,submit,type Preview,type Connection} from '../src/signing';
import {recipientAddress,NETWORKS,type Client} from '../src/chain';
import {walletAbi,entryAbi,tokenAbi} from '../src/abi';
import trusted from '../src/trusted-code.json';
const wallet=getAddress('0xbec9c3d164e2e8c640dc8efc330e92bafa6e7b07');
const owner=getAddress('0x1111111111111111111111111111111111111111');const backup=getAddress('0x2222222222222222222222222222222222222222');const token=getAddress('0x3333333333333333333333333333333333333333');
const raw=encodeAbiParameters([{type:'address'}],[owner]);const passkey=('0x'+'ab'.repeat(64)) as Hex;
function snapshot():Snapshot{return {wallet,chainId:1,block:100n,implementation:trusted.implementation as Address,implementationHash:trusted.implementationHash as Hex,proxyHash:trusted.proxyHash as Hex,verified:true,nextIndex:3n,count:2n,owners:[decodeOwner(0,passkey),decodeOwner(2,raw)],native:100n,entryPoint:trusted.entryPoint as Address,entryPointHash:trusted.entryPointHash as Hex,deposit:20n,stake:0n,checkedAt:Date.now()};}
function asset(kind:Asset['kind']='erc20'):Asset{return {key:kind,kind,contract:kind.startsWith('erc')?token:undefined,symbol:'TEST',name:'Test asset',decimals:kind==='erc20'?6:0,balance:100n,tokenId:kind==='erc721'||kind==='erc1155'?0n:undefined,source:'test'};}
describe('Owner preservation',()=>{
 it('decodes addresses and public keys without collapsing index gaps',()=>{expect(decodeOwner(2,raw).address).toBe(owner);expect(decodeOwner(0,passkey).kind).toBe('passkey');expect(decodeOwner(5,'0x1234').kind).toBe('unknown');});
 it('accepts an unchanged snapshot',()=>expect(()=>assertSameOwners(snapshot(),snapshot())).not.toThrow());
 it.each(['count','nextIndex','implementation','implementationHash','proxyHash','wallet','chainId'] as const)('rejects changed %s',key=>{const a=snapshot(),b=snapshot();(b as any)[key]=key==='chainId'?8453:typeof b[key]==='bigint'?8n:backup;expect(()=>assertSameOwners(a,b)).toThrow()});
 it('rejects a changed original passkey',()=>{const a=snapshot(),b=snapshot();b.owners[0].bytes=('0x'+'cd'.repeat(64)) as Hex;expect(()=>assertSameOwners(a,b)).toThrow('Owner configuration changed')});
 it('accepts exactly one appended backup owner with old indexes preserved',()=>{const a=snapshot(),b=snapshot();b.nextIndex=4n;b.count=3n;b.owners.push(decodeOwner(3,encodeAbiParameters([{type:'address'}],[backup])));expect(()=>assertAddition(a,b,backup)).not.toThrow()});
 it('rejects replacement of the original owner during an addition',()=>{const a=snapshot(),b=snapshot();b.nextIndex=4n;b.count=3n;b.owners[1]=decodeOwner(2,encodeAbiParameters([{type:'address'}],[backup]));b.owners.push(decodeOwner(3,encodeAbiParameters([{type:'address'}],[backup])));expect(()=>assertAddition(a,b,backup)).toThrow('existing owner changed')});
 it('rejects an incorrect appended owner',()=>{const a=snapshot(),b=snapshot();b.nextIndex=4n;b.count=3n;b.owners.push(decodeOwner(3,raw));expect(()=>assertAddition(a,b,backup)).toThrow('does not match')});
 it('blocks unreviewed code',()=>{const s=snapshot();s.verified=false;expect(()=>assertTrusted(s)).toThrow()});
 it('rejects an unregistered authorizing address',()=>expect(()=>actorRoute(snapshot(),backup)).toThrow());
 it('allows a registered EOA and the wallet self-call path',()=>{expect(actorRoute(snapshot(),owner)).toBe('eoa');expect(actorRoute(snapshot(),wallet)).toBe('self')});
});
describe('Recovery call construction',()=>{
 it('uses only the selected assets and a zero-value outer executeBatch',()=>{const s=snapshot();const native=asset('native');const dep=asset('deposit');dep.balance=20n;const erc20=asset();const nft=asset('erc721');const multi=asset('erc1155');const r=buildRecovery(s,backup,[{asset:native,amount:40n},{asset:dep,amount:20n},{asset:erc20,amount:25n},{asset:nft,amount:1n},{asset:multi,amount:2n}]);const outer=decodeFunctionData({abi:walletAbi,data:r.data});expect(outer.functionName).toBe('executeBatch');expect(r.calls).toHaveLength(5);expect(r.calls[0]).toEqual({target:backup,value:40n,data:'0x'});const d=decodeFunctionData({abi:entryAbi,data:r.calls[1].data});expect(d.functionName).toBe('withdrawTo');expect(d.args).toEqual([backup,20n]);expect(r.calls[1].target).toBe(s.entryPoint);expect(decodeFunctionData({abi:tokenAbi,data:r.calls[2].data}).functionName).toBe('transfer');expect(decodeFunctionData({abi:tokenAbi,data:r.calls[3].data}).args).toEqual([wallet,backup,0n]);expect(r.calls.slice(1).every(x=>x.value===0n)).toBe(true)});
 it('rejects duplicate selections',()=>{const x=asset();expect(()=>buildRecovery(snapshot(),backup,[{asset:x,amount:1n},{asset:x,amount:1n}])).toThrow('Duplicate')});
 it('rejects transfers to the wallet or zero address',()=>{expect(()=>recipientAddress(wallet,wallet)).toThrow();expect(()=>recipientAddress('0x'+'0'.repeat(40),wallet)).toThrow()});
 it('rejects a protected wallet token target',()=>{const a=asset();a.contract=wallet;expect(()=>buildRecovery(snapshot(),backup,[{asset:a,amount:1n}])).toThrow('Invalid token target')});
 it.each([0n,-1n,101n])('rejects amount %s',amount=>expect(()=>buildRecovery(snapshot(),backup,[{asset:asset(),amount}])).toThrow());
 it('rejects missing NFT IDs and invalid NFT quantities',()=>{const a=asset('erc721');a.tokenId=undefined;expect(()=>buildRecovery(snapshot(),backup,[{asset:a,amount:1n}])).toThrow();a.tokenId=0n;expect(()=>buildRecovery(snapshot(),backup,[{asset:a,amount:2n}])).toThrow()});
 it('rejects absent EntryPoint deposits',()=>{const s=snapshot();s.deposit=null;expect(()=>buildRecovery(s,backup,[{asset:asset('deposit'),amount:1n}])).toThrow('unavailable')});
 it('does not silently round fractional input',()=>{const a=asset();a.balance=1000000n;expect(amountFor(a,'0.000001')).toBe(1n);expect(()=>amountFor(a,'0.0000001')).toThrow('decimal places');expect(()=>amountFor(a,'1e-6')).toThrow();expect(()=>amountFor(a,'0')).toThrow()});
 it('rejects false-returning ERC-20 transfer simulations before the batch',async()=>{const call=vi.fn().mockResolvedValue({data:encodeAbiParameters([{type:'bool'}],[false])});const c={call,readContract:vi.fn().mockResolvedValue(100n)} as unknown as Client;await expect(simulateRecovery(c,snapshot(),owner,backup,[{asset:asset(),amount:1n}])).rejects.toThrow('did not return true');expect(call).toHaveBeenCalledTimes(1)});
 it('simulates the outer call after true-returning token checks',async()=>{const call=vi.fn().mockResolvedValue({data:encodeAbiParameters([{type:'bool'}],[true])});const c={call,readContract:vi.fn().mockResolvedValue(100n)} as unknown as Client;await simulateRecovery(c,snapshot(),owner,backup,[{asset:asset(),amount:1n}]);expect(call).toHaveBeenCalledTimes(2);expect(call.mock.calls[1][0].account).toBe(owner);expect(call.mock.calls[1][0].to).toBe(wallet)});
 it('rejects holdings that disappeared',async()=>{const c={readContract:vi.fn().mockResolvedValue(0n),call:vi.fn()} as unknown as Client;await expect(simulateRecovery(c,snapshot(),owner,backup,[{asset:asset(),amount:1n}])).rejects.toThrow('balance changed');expect(c.call).not.toHaveBeenCalled()});
});
describe('Signing boundaries',()=>{
 function preview():Preview{return {kind:'addition',snapshot:snapshot(),actor:owner,route:'eoa',data:encodeFunctionData({abi:walletAbi,functionName:'addOwnerAddress',args:[backup]}),calls:[],newOwner:backup,newOwnerContract:false,notes:[],createdAt:Date.now()}}
 it('does not submit from a different connected account',async()=>{const p=preview(),request=vi.fn().mockResolvedValue([backup]);await expect(submit({provider:{request},address:backup,name:'test'},NETWORKS[0],undefined,p,vi.fn(),vi.fn())).rejects.toThrow('exact authorizing');expect(request).toHaveBeenCalledTimes(1)});
 it('does not submit on a mismatched chain',async()=>{const request=vi.fn().mockResolvedValueOnce([owner]).mockResolvedValueOnce('0x2105');await expect(submit({provider:{request},address:owner,name:'test'},NETWORKS[0],undefined,preview(),vi.fn(),vi.fn())).rejects.toThrow('different chain');expect(request.mock.calls.some(([x])=>x.method==='eth_sendTransaction')).toBe(false)});
 it('requires contract-owner transactions to use the multisig flow',async()=>{const p=preview();p.route='contract';const request=vi.fn();await expect(submit({provider:{request},address:owner,name:'test'},NETWORKS[0],undefined,p,vi.fn(),vi.fn())).rejects.toThrow('multisig');expect(request).not.toHaveBeenCalled()});
 it('rejects a stale preview without reading or signing',async()=>{const p=preview();p.createdAt=Date.now()-360000;await expect(recheckPreview(NETWORKS[0],undefined,p)).rejects.toThrow('five minutes')});
 it('exports exact outer calldata with zero value and explicit chain',()=>{const p=preview();p.route='contract';const output=safeExport(p);expect(output.chainId).toBe('1');expect(output.transactions).toEqual([{to:wallet,value:'0',data:p.data,contractMethod:null,contractInputsValues:null}]);expect(decodeFunctionData({abi:walletAbi,data:output.transactions[0].data}).functionName).toBe('addOwnerAddress')});
});
