import fs from 'node:fs';
import {createPublicClient,http,keccak256,parseAbi,getAddress} from 'viem';
const wallet=getAddress('0xbec9c3d164e2e8c640dc8efc330e92bafa6e7b07');
const slot='0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc';
const abi=parseAbi(['function ownerAtIndex(uint256) view returns(bytes)','function nextOwnerIndex() view returns(uint256)','function ownerCount() view returns(uint256)','function entryPoint() view returns(address)','function balanceOf(address) view returns(uint256)']);
const urls={Ethereum:['https://ethereum-rpc.publicnode.com',1],Base:['https://base-rpc.publicnode.com',8453],Optimism:['https://optimism-rpc.publicnode.com',10],Arbitrum:['https://arbitrum-one-rpc.publicnode.com',42161],Polygon:['https://polygon.drpc.org',137],BSC:['https://bsc-rpc.publicnode.com',56],Avalanche:['https://avalanche-c-chain-rpc.publicnode.com',43114],Zora:['https://rpc.zora.energy',7777777],ApeChain:['https://rpc.apechain.com',33139],Monad:['https://rpc.monad.xyz',143]};
const verified=JSON.parse(fs.readFileSync('research/implementation.json'));const knownHash=keccak256(verified.deployed_bytecode);
const results=await Promise.all(Object.entries(urls).map(async([name,[url,chainId]])=>{
 try{
 const c=createPublicClient({transport:http(url,{timeout:15000,retryCount:1})});if(await c.getChainId()!==chainId)throw Error('chain mismatch');const block=await c.getBlockNumber();const code=await c.getCode({address:wallet,blockNumber:block});if(!code||code==='0x')return {name,chainId,deployed:false,block:block.toString()};const raw=await c.getStorageAt({address:wallet,slot,blockNumber:block});const implementation=getAddress('0x'+raw.slice(-40));const implCode=await c.getCode({address:implementation,blockNumber:block});const hash=keccak256(implCode);const read=(fn,args=[])=>c.readContract({address:wallet,abi,functionName:fn,args,blockNumber:block});const next=await read('nextOwnerIndex');const count=await read('ownerCount');if(next>1024n)throw Error('too many indexes');const owners=await Promise.all(Array.from({length:Number(next)},async(_,i)=>({index:i,bytes:await read('ownerAtIndex',[BigInt(i)])})));const ep=await read('entryPoint');const epCode=await c.getCode({address:ep,blockNumber:block});let deposit;try{deposit=(await c.readContract({address:ep,abi,functionName:'balanceOf',args:[wallet],blockNumber:block})).toString()}catch{deposit=null}
 return {name,chainId,deployed:true,block:block.toString(),implementation,implementationHash:hash,matchesVerifiedSource:hash===knownHash,proxyHash:keccak256(code),entryPoint:ep,entryPointHash:epCode&&epCode!=='0x'?keccak256(epCode):null,ownerCount:count.toString(),nextOwnerIndex:next.toString(),owners,deposit,nativeBalance:(await c.getBalance({address:wallet,blockNumber:block})).toString()};
 }catch(e){return {name,chainId,error:e.shortMessage||e.message}}
}));fs.writeFileSync('research/chain-verification.json',JSON.stringify({checkedAt:new Date().toISOString(),wallet,results},null,2));console.log(JSON.stringify(results,null,2));
const eth=results.find(r=>r.name==='Ethereum');if(eth?.matchesVerifiedSource){fs.writeFileSync('src/trusted-code.json',JSON.stringify({implementationHash:knownHash,proxyHash:eth.proxyHash,entryPointHash:eth.entryPointHash,implementation:eth.implementation,entryPoint:eth.entryPoint,sourceUrl:'https://eth.blockscout.com/address/'+eth.implementation+'?tab=contract',checkedAt:new Date().toISOString()},null,2))}
