import {useEffect,useState} from 'react';
import {Copy,Loader2} from 'lucide-react';
import {isAddress,type Address} from 'viem';
import {displayName,resolveAddress,type ResolvedAddress} from './ens';
import {short,errorText} from './chain';
export function useEnsName(value:string){const [result,setResult]=useState<{value:string;name:string|null}>({value:'',name:null});useEffect(()=>{let active=true;void displayName(value).then(name=>{if(active)setResult({value,name})});return()=>{active=false}},[value]);return result.value===value?result.name:null;}
export function AddressLine({value,onCopy,compact=false}:{value:string;onCopy?:(value:string)=>void;compact?:boolean}){const name=useEnsName(value);return <div className={`address-line ${compact?'compact-identity':''}`}><div className="identity-value">{name&&<div className="ens-name" title="ENS primary name verified against its Ethereum address">{name}</div>}<span className="mono" title={value}>{compact?short(value):value}</span></div>{onCopy&&<button className="icon-button" aria-label={`Copy ${value}`} onClick={()=>onCopy(value)}><Copy size={14}/></button>}</div>}
export function OwnerOption({address,index}:{address:Address;index:number}){const name=useEnsName(address);return <option value={address}>{name?`${name} · ${short(address)}`:short(address)} · owner #{index}</option>}
export function ResolutionHint({value}:{value:string}){const [result,setResult]=useState<{input:string;resolved?:ResolvedAddress;error?:string;loading?:boolean}>({input:''});const raw=value.trim();useEffect(()=>{let active=true;if(!raw||isAddress(raw,{strict:true})||!raw.includes('.')){setResult({input:raw});return;}setResult({input:raw,loading:true});const timer=setTimeout(()=>{void resolveAddress(raw).then(resolved=>{if(active)setResult({input:raw,resolved})}).catch(e=>{if(active)setResult({input:raw,error:errorText(e)})})},500);return()=>{active=false;clearTimeout(timer)}},[raw]);if(result.input!==raw)return null;if(result.loading)return <div className="section-note ens-hint"><Loader2 size={12} className="spinner"/>Resolving ENS on Ethereum…</div>;if(result.error)return <div className="section-note ens-error" role="status">{result.error}</div>;if(!result.resolved)return null;return <div className="ens-resolution"><span className="section-note">{result.resolved.name} resolves on Ethereum to</span><span className="mono">{result.resolved.address}</span></div>}
